<a href="https://colab.research.google.com/github/lingelizabeth/senior-research/blob/master/Final_Notebook_TESS_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**TESS Training and Evaluation**
This notebook trains a neural network on analyzed TESS ([Toronto Emotional Speech Set](https://tspace.library.utoronto.ca/handle/1807/24487)) speech data to predict 7 emotion classes. It utilizes a tiered model structure that first trains a Support Vector Machine to determine the possitive/negative affect of a sample, then uses that predicted label as input into a neural net. The final neural net accuracy is ~99% across all classes.

##**Load and clean data**
The inputs are CSV files generated by openSMILE, an audio feature extraction package, and they include statistical measures of audio characteristics for each sample. Specifically, I used the emobase feature set in the openSMILE toolkit.

In [ ]:
from scipy.io import *
import matplotlib.pyplot as plt
import numpy as np
import math
import os
import io
import pandas as pd
import random
from google.colab import files

from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split
from scipy.interpolate import *
from scipy.signal import *

from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
from sklearn import tree, svm, datasets
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import roc_curve, auc, confusion_matrix, accuracy_score
from itertools import cycle

import tensorflow as tf
from tensorflow.keras.layers import Dense, BatchNormalization
from tensorflow.keras.utils import to_categorical


In [ ]:
uploaded = files.upload() # upload CSV output of openSMILE run

In [ ]:
# read in CSV to pandas dataframe
df = pd.read_csv(io.StringIO(uploaded['TESSemobase.csv'].decode('utf-8')))

# use only every other line due to openSMILE output format
dropped = [i for i in range(1, df.shape[0], 2)]
df = df.drop(dropped)
df = df.reset_index()

# drop unneccessary columns
new_df = df.drop(['name', 'frameTime', 'index'], axis=1)

In [ ]:
# assigns each row as "positive" or "negative" emotion, based on its true label
positive = [] #1 for yes 0 for negative
for index, row in df.iterrows():
  if(int(row['emotion']) in [1, 2, 3, 8]): 
    positive.append(1)
  else:
    positive.append(0)
    
# append this column to the dataframe for later validation
new_df['positive'] = pd.Series(positive)

In [ ]:
# scale the data to have a mean of 0 and unit variance (standard deviation of 1)
scaler = StandardScaler()
scaled_new_df = scaler.fit_transform(new_df)

# fix indexing and drop labels for scaled dataframe
scaled_new_df = pd.DataFrame(scaled_new_df, index = range(0, scaled_new_df.shape[0]), columns = new_df.columns.values)
scaled_new_df = scaled_new_df.drop(['emotion', 'positive'], axis=1)
scaled_new_df

pcm_intensity_sma_max  ...  F0env_sma_de_iqr1-3
0                 -0.541741  ...             2.582346
1                 -0.518678  ...             0.221990
2                 -0.550113  ...             0.998991
3                 -0.496751  ...             5.215489
4                 -0.417006  ...             1.640690
5                 -0.373298  ...             2.512301
6                 -0.432746  ...             5.027295
7                 -0.517689  ...             4.130075
8                 -0.489338  ...             1.992210
9                 -0.459088  ...             1.212105
10                -0.047830  ...             5.016405
11                -0.392623  ...             1.425928
12                -0.154510  ...             1.912879
13                -0.534342  ...             1.922206
14                -0.482014  ...             1.181194
15                -0.482195  ...             0.530982
16                -0.481861  ...             1.129148
17                -0.484787  ...             3.172550
18                -0.528097  ...             0.109623
19                -0.483644  ...             0.619178
20                -0.472286  ...             0.846569
21                -0.567539  ...             1.680930
22                -0.546788  ...             2.498013
23                -0.372600  ...             0.771733
24                -0.533837  ...             1.106640
25                -0.557627  ...             1.140000
26                -0.504840  ...             1.553992
27                -0.545127  ...             2.197603
28                -0.365777  ...             1.180008
29                -0.424827  ...             4.234800
...                     ...  ...                  ...
2304               0.167917  ...             0.073852
2305               4.745868  ...            -0.181125
2306               0.639903  ...             0.348941
2307              -0.054539  ...            -0.171613
2308               0.109239  ...            -0.477955
2309              -0.009025  ...             0.005761
2310               0.208352  ...            -0.087619
2311               0.089585  ...             0.068961
2312              -0.045747  ...             0.230933
2313               0.184295  ...             0.076113
2314               0.404077  ...             0.164362
2315               1.321461  ...             0.125593
2316              -0.001820  ...             0.222758
2317               4.502588  ...            -0.481187
2318               0.259730  ...            -0.619437
2319               1.682352  ...            -0.276007
2320              -0.053783  ...            -0.236713
2321               0.487038  ...            -0.340381
2322              -0.345333  ...             0.005463
2323               0.274064  ...             0.625232
2324               0.749727  ...            -0.565239
2325               0.059815  ...             0.176349
2326               0.901382  ...             0.364245
2327               1.390593  ...            -0.238894
2328               0.996587  ...            -0.551365
2329               0.968789  ...            -0.502903
2330               1.143736  ...             0.567045
2331               2.175275  ...            -0.317962
2332              -0.615357  ...            -1.063290
2333              -0.609449  ...            -1.088728

[2334 rows x 988 columns]

## **Binary classification of positive and negative emotions**

My model architecture finding was a significant increase in emotion classification accuracy when first considering a binary classification: **is the sample "positive" or "negative"?** Emotions like happiness, surprise, and neutral were considered positive, while anger, fear, sadness, and disgust were considered negative. 

I use a Support Vector Machine for binary classification for this dataset. The overall accuracy is 98.3%.


In [ ]:
# split into training and validation data
X_train, X_val, y_train, y_val = train_test_split(scaled_new_df, new_df['positive'], test_size = .25, random_state = None)

# Gridsearch to determine best parameters
param_grid = {'C': [0.001, 0.01, 0.1, 1, 10], 'kernel': ['linear','rbf'], 'gamma':[0.001, 0.01, 0.1, 1]}
test_svm = svm.SVC(gamma='scale')
gridsearchsvm = GridSearchCV(test_svm, param_grid, cv=5)
gridsearchsvm.fit(X_train, y_train)


In [ ]:
#prints best parameters from Grid Search
gridsearchsvm.best_params_

{'C': 1, 'gamma': 0.001, 'kernel': 'rbf'}

In [ ]:
# create SVM classifier
svm = svm.SVC(C=1, gamma=.001, kernel='rbf')
svm.fit(X_train, y_train)
svm_y_predict = svm.predict(X_val)

# evaluate model, accuracy of 99.8%
print(confusion_matrix(y_val, svm_y_predict))
print(accuracy_score(y_val, svm_y_predict))

[[346   0]
 [  1 237]]
0.9982876712328768


### Confusion Matrix for Positive/Negative Classification

![SVM Confusion Matrix](https://drive.google.com/uc?export=view&id=1HwtaH8--zoBwOIaBrqj4bXQkUPRQQ_QM)

In [ ]:
# view which emotion classes are most often misclassified
misclassified = []
for i in range(len(y_predict)):
  if y_predict[i] != list(y_val)[i]:
    misclassified.append(new_df['emotion'][y_val.index[i]])
dict((x,misclassified.count(x)) for x in set(misclassified))

{'1': 7, '3': 1, '6': 2, '8': 9}

In this case, the most error comes from emotion classes 1 and 8, which represent neutral and pleasant surprise, respectively.

## **Classifying Emotions with a Neural Net**
Now, we will predict 7 emotion classes (happy, sad, neutral, fear, anger, disgust, and pleasant surprise) using a neural net, with the audio features *and* the previous positive/negative prediction as input. The final test accuracy is 98.97%.

In [ ]:
# add the svm binary predictions as an input column 
predicted_pos = svm.predict(scaled_new_df)
scaled_new_df['positive'] = pd.Series(predicted_pos)

# split training and testing data
train_data, val_data, train_labels, val_labels = 
  train_test_split(
      scaled_new_df.loc[X_train.index], 
      new_df.loc[y_train.index]['emotion'].astype(int)-1, 
      test_size = .5, 
      random_state = None
  )
print(train_data.shape)

# reshape the data for training 
train_data = np.array(train_data).reshape((train_data.shape[0], train_data.shape[1], 1))#normal_df.drop([' emotion '], axis=1).values.reshape((1403, 989, 1))
train_data.shape

(875, 989)


(875, 989, 1)

In [ ]:
# build model!
model = []
model = tf.keras.Sequential()
model.add(Dense(4, input_shape = train_data[0].shape))
model.add(Dense(4, activation='sigmoid', kernel_regularizer=tf.keras.regularizers.l2(0.01)))
model.add(tf.keras.layers.Dropout(.25))
model.add(BatchNormalization())
model.add(Dense(2, activation='relu'))
model.add(tf.keras.layers.Dropout(.2))
model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(8, activation = tf.nn.softmax)) 
  
sgd = tf.keras.optimizers.SGD(lr=0.001, momentum=0.0, decay=0.0, nesterov=False)
model.compile(optimizer = sgd, loss = 'categorical_crossentropy', metrics =["accuracy"])
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_4 (Dense)              (None, 989, 4)            8         
_________________________________________________________________
dense_5 (Dense)              (None, 989, 4)            20        
_________________________________________________________________
dropout_2 (Dropout)          (None, 989, 4)            0         
_________________________________________________________________
batch_normalization_v1_1 (Ba (None, 989, 4)            16        
_________________________________________________________________
dense_6 (Dense)              (None, 989, 2)            10        
_________________________________________________________________
dropout_3 (Dropout)          (None, 989, 2)            0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 1978)              0         
__________

In [ ]:
# train model
y = model.fit(train_data, to_categorical(train_labels), verbose = True, epochs = 120, validation_split = .2) 

Train on 700 samples, validate on 175 samples
Epoch 1/120
700/700 [==============================] - 0s 647us/sample - loss: 2.4999 - acc: 0.1571 - val_loss: 2.1520 - val_acc: 0.1314
Epoch 2/120
700/700 [==============================] - 0s 210us/sample - loss: 2.2886 - acc: 0.1986 - val_loss: 2.0967 - val_acc: 0.1600
Epoch 3/120
700/700 [==============================] - 0s 212us/sample - loss: 2.2549 - acc: 0.1971 - val_loss: 2.0356 - val_acc: 0.2000
Epoch 4/120
700/700 [==============================] - 0s 207us/sample - loss: 2.0760 - acc: 0.2314 - val_loss: 1.9655 - val_acc: 0.2343
Epoch 5/120
700/700 [==============================] - 0s 213us/sample - loss: 2.0003 - acc: 0.2529 - val_loss: 1.8776 - val_acc: 0.3086
Epoch 6/120
700/700 [==============================] - 0s 225us/sample - loss: 1.9854 - acc: 0.2729 - val_loss: 1.7694 - val_acc: 0.4229
Epoch 7/120
700/700 [==============================] - 0s 214us/sample - loss: 1.8279 - acc: 0.3214 - val_loss: 1.6519 - val_acc: 0.

In [ ]:
# Results on VALIDATION data from 2nd train test split
val_data = np.array(val_data).reshape((val_data.shape[0], val_data.shape[1], 1)) #reshape the validation data to input into the model

# predict and print evaluation metrics
y_pred_proba = model.predict(val_data)
print(confusion_matrix(val_labels, np.argmax(y_pred_proba, axis=1))) 
print(accuracy_score(val_labels, np.argmax(y_pred_proba, axis=1)))

[[ 62   0   6   0   0   0   0]
 [  0 131   0   0   0   0   7]
 [  0   0 164   0   0   0   0]
 [  0   0   0 132   0   0   0]
 [  0   0   0   1  88   0   1]
 [  0   0   0   0   0 145   1]
 [  0   2   0   0   2   1 132]]
0.976


In [ ]:
# Results on TEST data from 1st train test split

X_val_w_positive = X_val
X_val_predicted_pos = svm.predict(X_val) 
X_val_w_positive['positive'] = X_val_predicted_pos #add positive column to validation data
X_val_w_positive

# reshape the validation data to input into the model
X_val_w_positive = np.array(X_val_w_positive).reshape((X_val_w_positive.shape[0], X_val_w_positive.shape[1], 1)) 

# predict and print evaluation metrics
y_pred_X_val = model.predict(X_val_w_positive)
print(confusion_matrix(new_df.loc[y_val.index]['emotion'].astype(int)-1, np.argmax(y_pred_X_val, axis=1))) 
print(accuracy_score(new_df.loc[y_val.index]['emotion'].astype(int)-1, np.argmax(y_pred_X_val, axis=1)))

[[ 45   0   0   0   0   0   0]
 [  0 100   0   0   0   0   1]
 [  0   0 103   0   0   0   0]
 [  0   0   0  86   0   0   0]
 [  0   0   0   1  56   0   0]
 [  0   1   0   0   0  98   1]
 [  0   0   0   0   0   2  90]]
0.9897260273972602


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.


### Confusion Matrix for Multiclass Emotion Classification

![Neural Net Confusion Matrix](https://drive.google.com/uc?export=view&id=1z_d66o__bIVyKMkX1Q6DaM-gomVCz8bK)

## **Predicting on Real World Data**
Since the TESS model has relatively high test accuracy, I decided to test it on a short audio clip of my younger sister. The audio was run through openSMILE separately, with the CSV uploaded to this notebook. Below, you can see that the model predicts with 97% certainty that she is "pleasantly surprised".


In [ ]:
# read in CSV and drop unnecessary columns and label
test_data = pd.read_csv(io.StringIO(uploaded['tiffany_emobase.csv'].decode('utf-8')))
test_data = test_data.drop(['id', 'name', 'emotion', 'frameTime'], axis=1)

# predicting positive/negative affect and appending to sample
test_data['positive'] = svm.predict(test_data)
test_data

pcm_intensity_sma_max  pcm_intensity_sma_min  ...  F0env_sma_de_iqr1-3  positive
0               0.000053                    0.0  ...             3.523819         0

[1 rows x 989 columns]

In [ ]:
# predicting on test data
model.predict(np.array(test_data).reshape(test_data.shape[0], test_data.shape[1], 1))

array([[2.3528503e-07, 4.5681432e-08, 2.7178640e-02, 1.4097279e-07,
        3.5598394e-04, 4.4679781e-04, 1.0515617e-05, 9.7200769e-01]],
      dtype=float32)