<a href="https://colab.research.google.com/github/lingelizabeth/senior-research/blob/master/Final_Notebook_RAVDESS_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**RAVDESS Training and Evaluation**
This notebook trains a neural network on analyzed RAVDESS (Ryerson Audio-Visual Database of Emotional Speech and Song) speech data to predict 8 emotion classes. It utilizes a tiered model structure that first trains a Random Forest to determine the possitive/negative affect of a sample, then uses that predicted label as input into a neural net. The final neural net accuracy is 81.25% across all classes.

##**Load and clean data**
The inputs are CSV files generated by openSMILE, an audio feature extraction package, and they include statistical measures of audio characteristics for each sample.

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import math
import os
import io
import pandas as pd
import random
from sklearn import metrics
from google.colab import files

from scipy.interpolate import *
from scipy.signal import *
from scipy.io import *

from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split, GridSearchCV, KFold
from sklearn import tree
from sklearn import preprocessing
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from itertools import cycle

from sklearn import svm, datasets
from sklearn.metrics import roc_curve, auc, confusion_matrix, accuracy_score
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.utils import to_categorical

In [ ]:
uploaded = files.upload() # upload CSV output of openSMILE run

Saving emobaseResults.csv to emobaseResults.csv


In [ ]:
# read in CSV to pandas dataframe
df = pd.read_csv(io.StringIO(uploaded['emobaseResults.csv'].decode('utf-8')))

# use only every other line 
dropped = [i for i in range(1, 2804, 2)]
df = df.drop(dropped)
df = df.reindex(labels = range(1403), axis = 0, method = 'backfill')

# drop unneccessary columns
new_df = df.loc[:, ~df.columns.str.contains('^Unnamed')]
new_df = new_df.drop([' name ', ' frameTime '], axis=1)

In [ ]:
# assigns each row as "positive" or "negative" emotion, based on its actual classification
positive = [] # 1 for positive, 0 for negative
for index, row in df.iterrows():
  if(int(row[' emotion ']) in [1, 2, 3, 8]): 
    positive.append(1)
  else:
    positive.append(0)

# append this column to the dataframe for later validation
new_df['positive'] = pd.Series(positive)

In [ ]:
# scale the data to have a mean of 0 and unit variance (standard deviation of 1)
scaler = StandardScaler()
scaled_new_df = scaler.fit_transform(new_df)

# fix indexing and drop labels for scaled dataframe
scaled_new_df = pd.DataFrame(scaled_new_df, index = range(0, scaled_new_df.shape[0]), columns = new_df.columns.values)
scaled_new_df = scaled_new_df.drop([' emotion ', 'positive'], axis=1) # doesn't include labels, so we use this as training
scaled_new_df

pcm_intensity_sma_max   ...   F0env_sma_de_iqr1-3 
0                   -0.358004  ...              -0.855739
1                   -0.361132  ...              -0.855739
2                   -0.361132  ...              -0.855739
3                   -0.353465  ...              -0.855739
4                   -0.353465  ...              -0.855739
5                   -0.362988  ...              -0.855739
6                   -0.362988  ...              -0.855739
7                   -0.366114  ...              -0.855739
8                   -0.366114  ...              -0.855739
9                   -0.364902  ...              -0.824847
10                  -0.364902  ...              -0.824847
11                  -0.363935  ...              -0.855739
12                  -0.363935  ...              -0.855739
13                  -0.358483  ...              -0.855739
14                  -0.358483  ...              -0.855739
15                  -0.366996  ...              -0.855739
16                  -0.366996  ...              -0.855739
17                  -0.367356  ...              -0.780872
18                  -0.367356  ...              -0.780872
19                  -0.367285  ...              -0.855739
20                  -0.367285  ...              -0.855739
21                  -0.366147  ...              -0.855739
22                  -0.366147  ...              -0.855739
23                  -0.355493  ...              -0.855739
24                  -0.355493  ...              -0.855739
25                  -0.349888  ...              -0.583727
26                  -0.349888  ...              -0.583727
27                  -0.346490  ...              -0.855739
28                  -0.346490  ...              -0.855739
29                  -0.360551  ...              -0.855739
...                       ...  ...                    ...
1373                -0.333099  ...              -0.855739
1374                -0.333099  ...              -0.855739
1375                -0.327772  ...              -0.855739
1376                -0.327772  ...              -0.855739
1377                -0.325009  ...              -0.855739
1378                -0.325009  ...              -0.855739
1379                -0.285999  ...              -0.014832
1380                -0.285999  ...              -0.014832
1381                -0.240095  ...              -0.432213
1382                -0.240095  ...              -0.432213
1383                -0.286448  ...              -0.720570
1384                -0.286448  ...              -0.720570
1385                -0.358968  ...               0.059632
1386                -0.358968  ...               0.059632
1387                -0.361073  ...               0.447680
1388                -0.361073  ...               0.447680
1389                -0.354118  ...               2.335878
1390                -0.354118  ...               2.335878
1391                -0.362831  ...               0.602101
1392                -0.362831  ...               0.602101
1393                -0.366672  ...               1.008409
1394                -0.366672  ...               1.008409
1395                -0.359514  ...               0.130278
1396                -0.359514  ...               0.130278
1397                -0.367126  ...               1.719922
1398                -0.367126  ...               1.719922
1399                -0.366151  ...               0.018134
1400                -0.366151  ...               0.018134
1401                -0.364983  ...              -0.029749
1402                -0.364983  ...              -0.029749

[1403 rows x 988 columns]

## **Binary classification of positive and negative emotions**

My model architecture finding was a significant increase in emotion classification accuracy when first considering a binary classification: **is the sample "positive" or "negative"?** Emotions like happiness, surprise, neutral and calm were considered positive, while anger, fear, sadness, and disgust were considered negative. 

I use a Random Forest for binary classification for this dataset. The final accuracy is 92.88%


In [ ]:
# Gridsearch to determine best parameters
parameters = {'min_samples_split':[6, 7, 9], 'min_samples_leaf':[3, 4], 'max_features': [18, 20, 50]}
rf = RandomForestClassifier(n_estimators = 99, criterion = 'gini', max_depth = 7)
clf = GridSearchCV(rf, parameters, cv=5)
clf.fit(X_train, y_train)

GridSearchCV(cv=5, error_score='raise',
       estimator=RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=7, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=99, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'min_samples_split': [6, 7, 9], 'min_samples_leaf': [3, 4], 'max_features': [18, 20, 50]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [ ]:
#prints best parameters from Grid Search
clf.best_params_

{'max_features': 50, 'min_samples_leaf': 3, 'min_samples_split': 6}

In [ ]:
# split into training and validation data
X_train, X_val, y_train, y_val = train_test_split(scaled_new_df, new_df['positive'], test_size = .25, random_state = None)

# create random forest classifier
rf = RandomForestClassifier(n_estimators=99, criterion='gini', max_depth=7, min_samples_split = 6, min_samples_leaf=3, max_features=50, random_state=None)
rf.fit(X_train, y_train)
y_predict = rf.predict(X_val)

# evaluate model, accuracy of 92.8%
print(confusion_matrix(y_val, y_predict))
print(accuracy_score(y_val, y_predict))

[[171  12]
 [ 13 155]]
0.9287749287749287



### Confusion Matrix for Positive/Negative Classification


![Random Forest Conudsion Matrix](https://drive.google.com/uc?export=view&id=1HMGmkUdFmXY_KYRfD0EXe0TvzJQglu5m)

## **Classifying Emotions with a Neural Net**
Now, we will predict 8 emotion classes (happy, sad, neutral, calm, fear, anger, disgust, and surprise) using a neural net, with the audio features *and* the previous positive/negative prediction as input.

In [ ]:
# add the random forest predictions as an input column 
predicted_pos = rf.predict(scaled_new_df)
scaled_new_df['positive'] = pd.Series(predicted_pos)

# split training and testing data
train_data, val_data, train_labels, val_labels = 
  train_test_split(
      scaled_new_df.loc[X_train.index],  # this training data excludes test data from the previous split
      new_df.loc[y_train.index][' emotion '].astype(int)-1, 
      test_size = .2, 
      random_state = None
  )
print(train_data.shape)

# reshape the data for training 
train_data = np.array(train_data).reshape((train_data.shape[0], train_data.shape[1], 1))
train_data.shape

In [ ]:
# build model!
model = []
model = tf.keras.Sequential()
model.add(Dense(16, input_shape = train_data[0].shape))
model.add(Dense(16, activation='sigmoid', kernel_regularizer=tf.keras.regularizers.l2(0.01)))
model.add(tf.keras.layers.Dropout(.25))
model.add(Dense(4, activation='relu'))
model.add(tf.keras.layers.Dropout(.25))
model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(8, activation = tf.nn.softmax)) 
  
sgd = tf.keras.optimizers.SGD(lr=0.01, momentum=0.0, decay=0.001, nesterov=False)
model.compile(optimizer = sgd, loss = 'categorical_crossentropy', metrics =["accuracy"])
model.summary()

Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 989, 16)           32        
_________________________________________________________________
dense_1 (Dense)              (None, 989, 16)           272       
_________________________________________________________________
dropout (Dropout)            (None, 989, 16)           0         
_________________________________________________________________
dense_2 (Dense)              (None, 989, 4)            68        
_________________________________________________________________
dropout_1 (Dropout)          (None, 989, 4)            0         
_________________________________________________________________
flatten (Flatten)    

In [ ]:
y = model.fit(train_data, to_categorical(train_labels), verbose = True, epochs = 100, validation_split = .2) 

Train on 672 samples, validate on 169 samples
Instructions for updating:
Use tf.cast instead.
Epoch 1/100
672/672 [==============================] - 1s 1ms/sample - loss: 2.7825 - acc: 0.1354 - val_loss: 2.1601 - val_acc: 0.2012
Epoch 2/100
672/672 [==============================] - 0s 208us/sample - loss: 2.2424 - acc: 0.1786 - val_loss: 1.9896 - val_acc: 0.4083
Epoch 3/100
672/672 [==============================] - 0s 194us/sample - loss: 2.0920 - acc: 0.2440 - val_loss: 1.9019 - val_acc: 0.4083
Epoch 4/100
672/672 [==============================] - 0s 220us/sample - loss: 1.9760 - acc: 0.3155 - val_loss: 1.8414 - val_acc: 0.3669
Epoch 5/100
672/672 [==============================] - 0s 183us/sample - loss: 1.9356 - acc: 0.3229 - val_loss: 1.7001 - val_acc: 0.4260
Epoch 6/100
672/672 [==============================] - 0s 185us/sample - loss: 1.8391 - acc: 0.3810 - val_loss: 1.6328 - val_acc: 0.4970
Epoch 7/100
672/672 [==============================] - 0s 179us/sample - loss: 1.7249 

In [ ]:
# reshape validation data for model
val_data = np.array(val_data).reshape((val_data.shape[0], val_data.shape[1], 1))

# predict on validation data and print evaluations
y_pred_proba = model.predict(val_data)
print(confusion_matrix(val_labels, np.argmax(y_pred_proba, axis=1)))
print(accuracy_score(val_labels, np.argmax(y_pred_proba, axis=1)))

[[18  2  0  1  1  0  0  0]
 [ 0 52  0  1  0  0  0  0]
 [ 0  0 42  0  4  2  0  2]
 [ 0  0  0 36  0  3  0  0]
 [ 0  0  0  0 35  0  2  1]
 [ 1  0  0  1  0 39  0  1]
 [ 0  0  0  1  0  2 50  0]
 [ 0  0  0  0  0  0  0 54]]
0.9287749287749287


### K Fold Cross Validation
The output of this section has been omitted for brevity. The K-Fold cross validation accuracy was 98.29%.

In [ ]:
# get data and labels for K-fold cross validation 
data = np.array(scaled_new_df.loc[X_train.index])
all_labels= new_df.loc[y_train.index][' emotion '].astype(int)-1
print(len(data))

# prepare K-fold cross validation
kfold = KFold(3, False, 1)
# enumerate splits
for train, test in kfold.split(data):
  model.fit(data[train].reshape(len(train), data.shape[1], 1), to_categorical(all_labels.iloc[train]), verbose=True, epochs = 100, validation_split=.1)
  y_pred_temp = model.predict(data[test].reshape(len(test), data.shape[1], 1))
  print(accuracy_score(all_labels.iloc[test], np.argmax(y_pred_temp, axis=1))) # print validation accuracy per split
  model.reset_states()

### Final Model Evaluation
We evaluate the neural net test accuracy on data held back in the first data split, which neither the Random Forest or neural net has trained on.  

In [ ]:
X_val_predicted_pos = rf.predict(X_val) #add positive column to validation data
X_val_w_positive = X_val
X_val_w_positive['positive'] = X_val_predicted_pos

#reshape the validation data to input into the model
X_val_w_positive = np.array(X_val_w_positive).reshape((X_val_w_positive.shape[0], X_val_w_positive.shape[1], 1)) 

# predict on the data and print evaluation metrics
y_pred_X_val = model.predict(X_val_w_positive)
print(confusion_matrix(new_df.loc[y_val.index][' emotion '].astype(int)-1, np.argmax(y_pred_X_val, axis=1))) 
print(accuracy_score(new_df.loc[y_val.index][' emotion '].astype(int)-1, np.argmax(y_pred_X_val, axis=1)))

[[15  2  0  3  0  0  1  2]
 [ 3 52  0  1  0  0  0  0]
 [ 1  3 38  1  0  0  0  1]
 [ 0  3  0 35  0  0  3  2]
 [ 0  0  3  2 35  0  2  0]
 [ 0  3  1  0  0 41  0  1]
 [ 3  1  1  2  2  3 37  3]
 [ 0  1  1  3  0  3  0 37]]
0.8262108262108262


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.


![alt text](https://drive.google.com/uc?export=view&id=1WdRm1pI_de0eWPIEpiRastAUfwmp5OQJ)